// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class remove_fields_from_profile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_fields_from_profile));
        
        string IMigrationMetadata.Id
        {
            get { return "202201020155172_remove_fields_from_profile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
