// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_foreign_keys_and_refactor_fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_foreign_keys_and_refactor_fields));
        
        string IMigrationMetadata.Id
        {
            get { return "202201020135085_add_foreign_keys_and_refactor_fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
