// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_keys_and_refactor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_keys_and_refactor));
        
        string IMigrationMetadata.Id
        {
            get { return "202201020202193_add_keys_and_refactor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
