// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changeinmessage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeinmessage));
        
        string IMigrationMetadata.Id
        {
            get { return "202201072155171_change-in-message"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
